#!/usr/bin/env Rscript
# ==============================================================================
# Note: Upstream objects (chi_GTF, te_M, exon_gr, bigpicture_combineSE) are 
#       generated by the core TEDDY workflow and should be loaded in the environment.
# ==============================================================================

library(dplyr)
library(tidyr)
library(GenomicRanges)
library(rtracklayer)

#' @title Find TE regions and neighboring transcript regions associated with target TE-chimeric exons
#' @param object A GRanges object of target TE-chimeric exon regions.
#' @param te A GRanges object of TE annotations.
#' @param exon_gr A GRanges object of all exon annotations from the same transcriptome GTF.
#' @param te_names Optional character vector of TE names to keep, e.g. c("MTA_Mm", "MTA_Mm-int").
#' @param minoverlap Minimum overlap required by findOverlaps. Default is 15.
#' @param min_neighbor_width Minimum width required for same-exon flanking region. Default is 15.
FindAssociatedTE <- function(object,
                             te,
                             exon_gr,
                             te_names = NULL,
                             minoverlap = 15,
                             min_neighbor_width = 15) {
  
  if (!is.null(te_names)) {
    if (!"names" %in% colnames(S4Vectors::mcols(te))) {
      stop("The TE annotation must contain a metadata column named 'names'.")
    }
    te <- te[as.character(te$names) %in% te_names]
  }
  
  required_object_cols <- c("transcript_id", "gene_name", "tx_exon_rank")
  missing_object_cols <- setdiff(required_object_cols, colnames(S4Vectors::mcols(object)))
  if (length(missing_object_cols) > 0) {
    stop("object is missing required columns: ", paste(missing_object_cols, collapse = ", "))
  }
  
  required_exon_cols <- c("transcript_id", "gene_name", "exon_number")
  missing_exon_cols <- setdiff(required_exon_cols, colnames(S4Vectors::mcols(exon_gr)))
  if (length(missing_exon_cols) > 0) {
    stop("exon_gr is missing required columns: ", paste(missing_exon_cols, collapse = ", "))
  }
  
  overlaps <- GenomicRanges::findOverlaps(
    object,
    te,
    minoverlap = minoverlap
  )
  
  object_hit <- object[S4Vectors::queryHits(overlaps)]
  target_te <- te[S4Vectors::subjectHits(overlaps)]
  
  overlap_region <- GenomicRanges::pintersect(
    object_hit,
    target_te,
    ignore.strand = TRUE
  )
  
  result_tbl <- data.frame(
    object_index = S4Vectors::queryHits(overlaps),
    te_index = S4Vectors::subjectHits(overlaps),
    
    object_seqnames = as.character(GenomicRanges::seqnames(object_hit)),
    object_start = GenomicRanges::start(object_hit),
    object_end = GenomicRanges::end(object_hit),
    object_strand = as.character(GenomicRanges::strand(object_hit)),
    
    TE_seqnames = as.character(GenomicRanges::seqnames(target_te)),
    TE_start = GenomicRanges::start(target_te),
    TE_end = GenomicRanges::end(target_te),
    TE_strand = as.character(GenomicRanges::strand(target_te)),
    
    overlap_seqnames = as.character(GenomicRanges::seqnames(overlap_region)),
    overlap_start = GenomicRanges::start(overlap_region),
    overlap_end = GenomicRanges::end(overlap_region),
    overlap_strand = as.character(GenomicRanges::strand(object_hit)),
    
    transcript_id = as.character(object_hit$transcript_id),
    gene_name = as.character(object_hit$gene_name),
    tx_exon_rank = as.integer(object_hit$tx_exon_rank),
    stringsAsFactors = FALSE
  )
  
  if ("names" %in% colnames(S4Vectors::mcols(target_te))) {
    result_tbl$TE_name <- as.character(target_te$names)
  }
  if ("family" %in% colnames(S4Vectors::mcols(target_te))) {
    result_tbl$TE_family <- as.character(target_te$family)
  }
  if ("class" %in% colnames(S4Vectors::mcols(target_te))) {
    result_tbl$TE_class <- as.character(target_te$class)
  }
  
  exon_tbl <- as.data.frame(exon_gr) %>%
    dplyr::transmute(
      exon_seqnames = as.character(seqnames),
      exon_start = start,
      exon_end = end,
      exon_strand = as.character(strand),
      transcript_id = as.character(transcript_id),
      gene_name = as.character(gene_name),
      exon_number = as.integer(exon_number)
    ) %>%
    dplyr::filter(
      !is.na(transcript_id),
      !is.na(gene_name),
      !is.na(exon_number)
    ) %>%
    dplyr::distinct()
  
  result_tbl <- result_tbl %>%
    dplyr::mutate(
      left_same_exon_width = overlap_start - object_start,
      right_same_exon_width = object_end - overlap_end,
      
      left_neighbor_type = dplyr::if_else(
        left_same_exon_width >= min_neighbor_width,
        "same_exon_left_flank",
        "upstream_exon"
      ),
      right_neighbor_type = dplyr::if_else(
        right_same_exon_width >= min_neighbor_width,
        "same_exon_right_flank",
        "downstream_exon"
      ),
      
      left_neighbor_start = dplyr::if_else(
        left_same_exon_width >= min_neighbor_width,
        object_start,
        NA_integer_
      ),
      left_neighbor_end = dplyr::if_else(
        left_same_exon_width >= min_neighbor_width,
        overlap_start - 1L,
        NA_integer_
      ),
      right_neighbor_start = dplyr::if_else(
        right_same_exon_width >= min_neighbor_width,
        overlap_end + 1L,
        NA_integer_
      ),
      right_neighbor_end = dplyr::if_else(
        right_same_exon_width >= min_neighbor_width,
        object_end,
        NA_integer_
      )
    )
  
  upstream_exon_tbl <- exon_tbl %>%
    dplyr::rename(
      upstream_seqnames = exon_seqnames,
      upstream_start = exon_start,
      upstream_end = exon_end,
      upstream_strand = exon_strand,
      upstream_exon_rank = exon_number
    )
  
  downstream_exon_tbl <- exon_tbl %>%
    dplyr::rename(
      downstream_seqnames = exon_seqnames,
      downstream_start = exon_start,
      downstream_end = exon_end,
      downstream_strand = exon_strand,
      downstream_exon_rank = exon_number
    )
  
  result_tbl <- result_tbl %>%
    dplyr::mutate(
      upstream_exon_rank = tx_exon_rank - 1L,
      downstream_exon_rank = tx_exon_rank + 1L
    ) %>%
    dplyr::left_join(
      upstream_exon_tbl,
      by = c("transcript_id", "gene_name", "upstream_exon_rank")
    ) %>%
    dplyr::left_join(
      downstream_exon_tbl,
      by = c("transcript_id", "gene_name", "downstream_exon_rank")
    ) %>%
    dplyr::mutate(
      left_neighbor_seqnames = dplyr::if_else(
        left_neighbor_type == "same_exon_left_flank",
        object_seqnames,
        upstream_seqnames
      ),
      left_neighbor_start = dplyr::if_else(
        left_neighbor_type == "same_exon_left_flank",
        left_neighbor_start,
        upstream_start
      ),
      left_neighbor_end = dplyr::if_else(
        left_neighbor_type == "same_exon_left_flank",
        left_neighbor_end,
        upstream_end
      ),
      left_neighbor_strand = dplyr::if_else(
        left_neighbor_type == "same_exon_left_flank",
        object_strand,
        upstream_strand
      ),
      
      right_neighbor_seqnames = dplyr::if_else(
        right_neighbor_type == "same_exon_right_flank",
        object_seqnames,
        downstream_seqnames
      ),
      right_neighbor_start = dplyr::if_else(
        right_neighbor_type == "same_exon_right_flank",
        right_neighbor_start,
        downstream_start
      ),
      right_neighbor_end = dplyr::if_else(
        right_neighbor_type == "same_exon_right_flank",
        right_neighbor_end,
        downstream_end
      ),
      right_neighbor_strand = dplyr::if_else(
        right_neighbor_type == "same_exon_right_flank",
        object_strand,
        downstream_strand
      )
    )
  
  te_bed <- result_tbl %>%
    dplyr::mutate(
      chrom = overlap_seqnames,
      chromStart = overlap_start - 1L,
      chromEnd = overlap_end,
      name = paste(
        transcript_id, gene_name, TE_name,
        paste0("rank", tx_exon_rank),
        paste0("obj", object_index),
        paste0("te", te_index),
        sep = "|"
      ),
      score = 0,
      strand = overlap_strand
    ) %>%
    dplyr::select(chrom, chromStart, chromEnd, name, score, strand) %>%
    dplyr::distinct()
  
  left_neighbor_bed <- result_tbl %>%
    dplyr::filter(
      !is.na(left_neighbor_seqnames),
      !is.na(left_neighbor_start),
      !is.na(left_neighbor_end),
      left_neighbor_end >= left_neighbor_start
    ) %>%
    dplyr::mutate(
      chrom = left_neighbor_seqnames,
      chromStart = left_neighbor_start - 1L,
      chromEnd = left_neighbor_end,
      name = paste(
        transcript_id, gene_name, TE_name,
        paste0("rank", tx_exon_rank),
        "left_neighbor", left_neighbor_type,
        sep = "|"
      ),
      score = 0,
      strand = left_neighbor_strand
    ) %>%
    dplyr::select(chrom, chromStart, chromEnd, name, score, strand) %>%
    dplyr::distinct()
  
  right_neighbor_bed <- result_tbl %>%
    dplyr::filter(
      !is.na(right_neighbor_seqnames),
      !is.na(right_neighbor_start),
      !is.na(right_neighbor_end),
      right_neighbor_end >= right_neighbor_start
    ) %>%
    dplyr::mutate(
      chrom = right_neighbor_seqnames,
      chromStart = right_neighbor_start - 1L,
      chromEnd = right_neighbor_end,
      name = paste(
        transcript_id, gene_name, TE_name,
        paste0("rank", tx_exon_rank),
        "right_neighbor", right_neighbor_type,
        sep = "|"
      ),
      score = 0,
      strand = right_neighbor_strand
    ) %>%
    dplyr::select(chrom, chromStart, chromEnd, name, score, strand) %>%
    dplyr::distinct()
  
  return(list(
    overlap_table = result_tbl,
    object_hit = object_hit,
    target_te = target_te,
    overlap_region = overlap_region,
    te_bed = te_bed,
    left_neighbor_bed = left_neighbor_bed,
    right_neighbor_bed = right_neighbor_bed
  ))
}

#' @title Format associated TE objects into a consolidated bed-like table
make_associated_te_support_bed <- function(associated_obj) {
  
  tbl <- associated_obj$overlap_table %>%
    mutate(
      pair_id = paste(
        transcript_id, gene_name, TE_name,
        paste0("rank", tx_exon_rank),
        paste0("obj", object_index),
        paste0("te", te_index),
        sep = "|"
      )
    )
  
  te_region <- tbl %>%
    transmute(
      chrom = overlap_seqnames,
      chromStart = overlap_start - 1L,
      chromEnd = overlap_end,
      name = pair_id,
      score = 0,
      strand = overlap_strand,
      pair_id = pair_id,
      region_role = "TE_overlap",
      transcript_id,
      gene_name,
      TE_name,
      tx_exon_rank,
      neighbor_type = "TE_overlap"
    )
  
  left_region <- tbl %>%
    filter(
      !is.na(left_neighbor_seqnames),
      !is.na(left_neighbor_start),
      !is.na(left_neighbor_end),
      left_neighbor_end >= left_neighbor_start
    ) %>%
    transmute(
      chrom = left_neighbor_seqnames,
      chromStart = left_neighbor_start - 1L,
      chromEnd = left_neighbor_end,
      name = pair_id,
      score = 0,
      strand = left_neighbor_strand,
      pair_id = pair_id,
      region_role = "left_neighbor",
      transcript_id,
      gene_name,
      TE_name,
      tx_exon_rank,
      neighbor_type = left_neighbor_type
    )
  
  right_region <- tbl %>%
    filter(
      !is.na(right_neighbor_seqnames),
      !is.na(right_neighbor_start),
      !is.na(right_neighbor_end),
      right_neighbor_end >= right_neighbor_start
    ) %>%
    transmute(
      chrom = right_neighbor_seqnames,
      chromStart = right_neighbor_start - 1L,
      chromEnd = right_neighbor_end,
      name = pair_id,
      score = 0,
      strand = right_neighbor_strand,
      pair_id = pair_id,
      region_role = "right_neighbor",
      transcript_id,
      gene_name,
      TE_name,
      tx_exon_rank,
      neighbor_type = right_neighbor_type
    )
  
  bind_rows(te_region, left_region, right_region) %>%
    distinct()
}

#' @title Collapse TE and flanking support regions by unique locus ID
collapse_mta_support_by_locus <- function(mta_support_tbl) {
  make_region_string <- function(chrom, start, end, type, tx, gene, rank) {
    ok <- !is.na(chrom) & !is.na(start) & !is.na(end)
    out <- rep(NA_character_, length(chrom))
    out[ok] <- paste(
      chrom[ok],
      paste0(start[ok], "-", end[ok]),
      type[ok],
      tx[ok],
      gene[ok],
      paste0("rank", rank[ok]),
      sep = "|"
    )
    out
  }
  
  mta_support_tbl %>%
    mutate(
      locus_id = paste(
        TE_chrom = chrom[region_role == "TE_overlap"],
        paste0(chromStart[region_role == "TE_overlap"] + 1L, "-", chromEnd[region_role == "TE_overlap"]),
        TE_name = TE_name[region_role == "TE_overlap"],
        sep = "|"
      ),
      left_region = make_region_string(
        chrom[region_role == "left_neighbor"],
        chromStart[region_role == "left_neighbor"] + 1L,
        chromEnd[region_role == "left_neighbor"],
        neighbor_type[region_role == "left_neighbor"],
        transcript_id[region_role == "left_neighbor"],
        gene_name[region_role == "left_neighbor"],
        tx_exon_rank[region_role == "left_neighbor"]
      ),
      right_region = make_region_string(
        chrom[region_role == "right_neighbor"],
        chromStart[region_role == "right_neighbor"] + 1L,
        chromEnd[region_role == "right_neighbor"],
        neighbor_type[region_role == "right_neighbor"],
        transcript_id[region_role == "right_neighbor"],
        gene_name[region_role == "right_neighbor"],
        tx_exon_rank[region_role == "right_neighbor"]
      )
    ) %>%
    group_by(locus_id, TE_name, strand) %>%
    summarise(
      chrom = first(chrom[region_role == "TE_overlap"]),
      chromStart = first(chromStart[region_role == "TE_overlap"]),
      chromEnd = first(chromEnd[region_role == "TE_overlap"]),
      name = first(locus_id),
      score = 0,
      transcript_ids = paste(unique(transcript_id), collapse = ";"),
      gene_names = paste(unique(gene_name), collapse = ";"),
      tx_exon_ranks = paste(unique(tx_exon_rank), collapse = ";"),
      left_neighbor_regions = paste(unique(na.omit(left_region)), collapse = ";"),
      right_neighbor_regions = paste(unique(na.omit(right_region)), collapse = ";"),
      n_transcripts = n_distinct(transcript_id),
      n_left_neighbors = n_distinct(na.omit(left_region)),
      n_right_neighbors = n_distinct(na.omit(right_region)),
      .groups = "drop"
    ) %>%
    select(
      chrom, chromStart, chromEnd, name, score, strand,
      locus_id, TE_name,
      transcript_ids, gene_names, tx_exon_ranks,
      left_neighbor_regions, right_neighbor_regions,
      n_transcripts, n_left_neighbors, n_right_neighbors
    )
}


# ==============================================================================
# Execution Block
# ==============================================================================

# 1. Identify associated TE boundaries
mta_associated <- FindAssociatedTE(
  object = chi_GTF,
  te = te_M,
  exon_gr = exon_gr,
  te_names = c("MTA_Mm", "MTA_Mm-int"),
  minoverlap = 15,
  min_neighbor_width = 15
)

# 2. Format into support regions
mta_support_bed <- make_associated_te_support_bed(mta_associated)

# 3. Collapse regions by unique locus ID
mta_locus_support_tbl <- collapse_mta_support_by_locus(mta_support_bed)

# Output strictly supported loci definition file
write.table(
  mta_locus_support_tbl,
  file = "MTA_locus_neighbor_support_table.tsv",
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  col.names = TRUE
)


cat("Successfully generated support table and junction windows.\n")